<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>fileTypes</key>
  <array>
    <string>sparx</string>
    <string>spk</string>
  </array>
  <key>name</key>
  <string>Sparx</string>
  <key>patterns</key>
  <array>
    <dict>
      <key>include</key>
      <string>#comments</string>
    </dict>
    <dict>
      <key>include</key>
      <string>#headings</string>
    </dict>
    <dict>
      <key>include</key>
      <string>#containers</string>
    </dict>
    <dict>
      <key>include</key>
      <string>#lists</string>
    </dict>
    <dict>
      <key>include</key>
      <string>#responsive-images</string>
    </dict>
    <dict>
      <key>include</key>
      <string>#images</string>
    </dict>
    <dict>
      <key>include</key>
      <string>#links</string>
    </dict>
    <dict>
      <key>include</key>
      <string>#citations</string>
    </dict>
    <dict>
      <key>include</key>
      <string>#code</string>
    </dict>
    <dict>
      <key>include</key>
      <string>#tables</string>
    </dict>
    <dict>
      <key>include</key>
      <string>#inline-formatting</string>
    </dict>
    <dict>
      <key>include</key>
      <string>#misc-inline</string>
    </dict>
  </array>
  <key>repository</key>
  <dict>
    <key>comments</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>match</key>
          <string>^#\s.*$</string>
          <key>name</key>
          <string>comment.line.sparx</string>
        </dict>
      </array>
    </dict>
    <key>headings</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>entity.name.section.sparx</string>
              <key>patterns</key>
              <array>
                <dict>
                  <key>include</key>
                  <string>#inline-formatting</string>
                </dict>
              </array>
            </dict>
          </dict>
          <key>match</key>
          <string>^#\s+(.+)$</string>
          <key>name</key>
          <string>markup.heading.1.sparx</string>
        </dict>
        <dict>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>entity.name.section.sparx</string>
              <key>patterns</key>
              <array>
                <dict>
                  <key>include</key>
                  <string>#inline-formatting</string>
                </dict>
              </array>
            </dict>
          </dict>
          <key>match</key>
          <string>^##\s+(.+)$</string>
          <key>name</key>
          <string>markup.heading.2.sparx</string>
        </dict>
        <dict>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>entity.name.section.sparx</string>
              <key>patterns</key>
              <array>
                <dict>
                  <key>include</key>
                  <string>#inline-formatting</string>
                </dict>
              </array>
            </dict>
          </dict>
          <key>match</key>
          <string>^###\s+(.+)$</string>
          <key>name</key>
          <string>markup.heading.3.sparx</string>
        </dict>
        <dict>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>entity.name.section.sparx</string>
              <key>patterns</key>
              <array>
                <dict>
                  <key>include</key>
                  <string>#inline-formatting</string>
                </dict>
              </array>
            </dict>
          </dict>
          <key>match</key>
          <string>^####\s+(.+)$</string>
          <key>name</key>
          <string>markup.heading.4.sparx</string>
        </dict>
        <dict>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>entity.name.section.sparx</string>
              <key>patterns</key>
              <array>
                <dict>
                  <key>include</key>
                  <string>#inline-formatting</string>
                </dict>
              </array>
            </dict>
          </dict>
          <key>match</key>
          <string>^#####\s+(.+)$</string>
          <key>name</key>
          <string>markup.heading.5.sparx</string>
        </dict>
        <dict>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>entity.name.section.sparx</string>
              <key>patterns</key>
              <array>
                <dict>
                  <key>include</key>
                  <string>#inline-formatting</string>
                </dict>
              </array>
            </dict>
          </dict>
          <key>match</key>
          <string>^######\s+(.+)$</string>
          <key>name</key>
          <string>markup.heading.6.sparx</string>
        </dict>
      </array>
    </dict>
    <key>containers</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>begin</key>
          <string>^(\$)\[([a-zA-Z][a-zA-Z0-9_-]*)\]\{</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.definition.container.begin.sparx</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>entity.name.section.sparx</string>
            </dict>
          </dict>
          <key>end</key>
          <string>^\}</string>
          <key>endCaptures</key>
          <dict>
            <key>0</key>
            <dict>
              <key>name</key>
              <string>punctuation.definition.container.end.sparx</string>
            </dict>
          </dict>
          <key>name</key>
          <string>meta.container.section.sparx</string>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>$self</string>
            </dict>
          </array>
        </dict>
        <dict>
          <key>begin</key>
          <string>^(>)(?:\[([^\]]+)\])?\{</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.definition.container.begin.sparx</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>string.other.link.sparx</string>
            </dict>
          </dict>
          <key>end</key>
          <string>^\}</string>
          <key>endCaptures</key>
          <dict>
            <key>0</key>
            <dict>
              <key>name</key>
              <string>punctuation.definition.container.end.sparx</string>
            </dict>
          </dict>
          <key>name</key>
          <string>meta.container.blockquote.sparx</string>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>$self</string>
            </dict>
          </array>
        </dict>
        <dict>
          <key>begin</key>
          <string>^(\.)([a-zA-Z0-9_-]+)\{</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.definition.container.begin.sparx</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>entity.name.class.sparx</string>
            </dict>
          </dict>
          <key>end</key>
          <string>^\}</string>
          <key>endCaptures</key>
          <dict>
            <key>0</key>
            <dict>
              <key>name</key>
              <string>punctuation.definition.container.end.sparx</string>
            </dict>
          </dict>
          <key>name</key>
          <string>meta.container.div.sparx</string>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>$self</string>
            </dict>
          </array>
        </dict>
        <dict>
          <key>begin</key>
          <string>^(~)\{</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.definition.container.begin.sparx</string>
            </dict>
          </dict>
          <key>end</key>
          <string>^\}</string>
          <key>endCaptures</key>
          <dict>
            <key>0</key>
            <dict>
              <key>name</key>
              <string>punctuation.definition.container.end.sparx</string>
            </dict>
          </dict>
          <key>name</key>
          <string>meta.container.aside.sparx</string>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>$self</string>
            </dict>
          </array>
        </dict>
        <dict>
          <key>begin</key>
          <string>^(f)\[([^\]]+)\]\{</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.definition.container.begin.sparx</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>string.quoted.sparx</string>
            </dict>
          </dict>
          <key>end</key>
          <string>^\}</string>
          <key>endCaptures</key>
          <dict>
            <key>0</key>
            <dict>
              <key>name</key>
              <string>punctuation.definition.container.end.sparx</string>
            </dict>
          </dict>
          <key>name</key>
          <string>meta.container.figure.sparx</string>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>$self</string>
            </dict>
          </array>
        </dict>
        <dict>
          <key>begin</key>
          <string>^(\+)\[([^\]]+)\]\{</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.definition.container.begin.sparx</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>string.quoted.sparx</string>
            </dict>
          </dict>
          <key>end</key>
          <string>^\}</string>
          <key>endCaptures</key>
          <dict>
            <key>0</key>
            <dict>
              <key>name</key>
              <string>punctuation.definition.container.end.sparx</string>
            </dict>
          </dict>
          <key>name</key>
          <string>meta.container.details.sparx</string>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>$self</string>
            </dict>
          </array>
        </dict>
      </array>
    </dict>
    <!-- I'll continue with the rest if this works! -->
  </dict>
  <key>scopeName</key>
  <string>source.sparx</string>
</dict>
</plist>